package com.example.rating.service.RatingService.entities;

import org.springframework.data.annotation.Id; //see not from JPA but from Spring Data
import org.springframework.data.mongodb.core.mapping.Document;

//@Entity- MYSQL Table -uses JPA
//MongoDB - Data is stored in collections in MongoDB
//user_ratings - collection with name created in MongoDB where data will be stored
@Document("user_ratings")
public class Rating {

    //same fields as in User Service Rating class
    @Id
    private String ratingId; //rating id - in mongoDB id is generated by default

    private String userId;    //kis user ne rate kiya
    private String hotelId;   //kis hotel ki rating hai
    private int rating;      //1 star, 2 star
    private String feedback;









    //getters and setters
    public String getRatingId() {
        return ratingId; 
    }

    public void setRatingId(String ratingId) {
        this.ratingId = ratingId;
    }

    public String getHotelId() {
        return hotelId;
    }

    public void setHotelId(String hotelId) {
        this.hotelId = hotelId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getFeedback() {
        return feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public Rating(String ratingId, String userId, String hotelId, int rating, String feedback) {
        this.ratingId = ratingId;
        this.userId = userId;
        this.hotelId = hotelId;
        this.rating = rating;
        this.feedback = feedback;
    }

    public Rating() {
    }
}